name: Deploy Worker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate Wrangler (Cloudflare action)
        uses: cloudflare/wrangler-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Publish to Cloudflare
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler deploy

      - name: Smoke test deployed worker
        if: ${{ success() }}
        run: |
          ./scripts/smoke_test.sh
        shell: bash
